services:  # containers. same as docker run
  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports: 
      - 80:80
    networks: 
      - frontend

  redis:
    image: redis:3.2
    networks:
      - frontend
  
  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - frontend
      - backend

  db:
    image: postgres:9.4
    environment: 
      - POSTGRES_PASSWORD=test
    networks:
      - backend

  
  result:
    image: dockersamples/examplevotingapp_result:before
    ports:
      - 5001:80
    networks:
      - backend

volumes: /var/lib/postgresql/data

