# create your drupal and postgres config here, based off the last assignment

version: '3.1'  # if no version is specificed then v1 is assumed. Recommend v2 minimum

services:  # containers. same as docker run
  drupal:
    image: custom-drupal
    build: . 
    ports: 
      - "8080:80"
    volumes: 
      - modules:/var/www/html/modules
      - profiles:/var/www/html/profiles
      - themes:/var/www/html/themes
      - sites:/var/www/html/sites
      - data:/var/lib/postgresql/data
  postgres:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=test

volumes:
  data:
  modules:
  profiles:
  themes:
  sites:


